config/routes.rb
RjcropCarrierwave::Application.routes.draw do
  resources :users do
    member do
      get 'crop'
    end
  end

  root :to => "users#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  validates_integrity_of :image

  after_update :reprocess_image, :if => :cropping?

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  private
  def reprocess_image
    image.reprocess!(crop_x, crop_y, crop_w, crop_h)
    store_image!
    image.recreate_versions!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      if params[:user][:image].present?
        render :action => 'cropping'
      else
        redirect_to(@user, :notice => 'User was successfully created.')
      end
    else
      render :action => "new"
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      if params[:user][:image].present?
        render :action => 'cropping'
      else
        redirect_to(@user, :notice => 'User was successfully updated.')
      end
    else
      render :action => "edit"
    end
  end

  def crop
    @user = User.find(params[:id])
    render :action => 'cropping'
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to(users_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RjcropCarrierwave</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.5.1.min', 'rails' %>
  <%= yield :headers %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:multipart => true}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inputs">
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :image %>
      <%= f.file_field :image %>
    </p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/cropping.html.erb
<%= content_for :headers do %>
<%= javascript_include_tag 'jquery.Jcrop.min' %>
<%= stylesheet_link_tag 'jquery.Jcrop' %>
<script language="Javascript">

function showPreview(coords)
{
	var rx = <%= ImageUploader::THUMB_W %> / coords.w;
	var ry = <%= ImageUploader::THUMB_H %> / coords.h;
	var ratio = <%= @user.image.width %> / <%= @user.image.normal.width %>; 

	$('#preview').css({
		width: Math.round(rx * <%= @user.image.normal.width %>) + 'px',
		height: Math.round(ry * <%= @user.image.normal.height %>) + 'px',
		marginLeft: '-' + Math.round(rx * coords.x) + 'px',
		marginTop: '-' + Math.round(ry * coords.y) + 'px'
	});
  $('#crop_x').val(Math.round(coords.x * ratio));
  $('#crop_y').val(Math.round(coords.y * ratio));
  $('#crop_w').val(Math.round(coords.w * ratio));
  $('#crop_h').val(Math.round(coords.h * ratio));
}

$(function() {
  $('#cropbox').Jcrop({
      onSelect: showPreview,
      onChange: showPreview,
      setSelect:   [ 0, 0, 240, 240 ],
      aspectRatio: <%= ImageUploader::THUMB_W %>/<%= ImageUploader::THUMB_H %>
    });
});

</script>
<% end %>

<p>
  <b>Name:</b>
  <%=h @user.name %>
</p>

<p>
  <b>Avatar:</b>
  <%= image_tag @user.image.normal.url, :id => 'cropbox' %>
<div style="width:<%= ImageUploader::THUMB_W %>px;height:<%= ImageUploader::THUMB_H %>px;overflow:hidden">
  <%= image_tag @user.image.normal.url, :id => 'preview' %>
</div>
</p>

<%= form_for @user do |f| %>
  <%= f.text_field :crop_x, :id => 'crop_x' %><br />
  <%= f.text_field :crop_y, :id => 'crop_y' %><br />
  <%= f.text_field :crop_w, :id => 'crop_w' %><br />
  <%= f.text_field :crop_h, :id => 'crop_h' %><br />
  <%= f.submit "Crop!" %>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Crop', crop_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @user.name %></h3>
<p> <%= image_tag @user.image.thumb.url %> </p>
<p> <%= image_tag @user.image.normal.url %> </p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<p> <%= image_tag @user.image.url, :style => 'max-width: 800px' %> </p>